# Generated by Django 5.0.1 on 2025-03-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studentupdate',
        ),
    ]
